apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment # all pods derive their names from this, then replicaset hash and unique characters for each pod
spec: # deployment specification
  replicas: 4
  selector:
    matchLabels:
      app: website # should match template's metadata label
  template: # instructions on how to create pods
    metadata:
      labels:
        app: website
    spec: # pod specifications
      containers:
        - name: website-container # specific container name in the pod
          image: rocketman02/updated-website:v1
          resources: # cpu & ram limits for each container
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 80

---
# service
apiVersion: v1
kind: Service
metadata:
  name: website-service
spec:
  type: NodePort
  selector:
    app: website # targetting all pods with this label
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30011
